### PR TITLE
feat: hide window

### PR DESCRIPTION
**Pull request by tuananh**
hide window on `Cmd + H`

Fixes: #60

### CODE REVIEW

**Comment by tuananh** [comment]
Not sure if I should set Ctrl H to hide on Windows/Linux though.

**Comment by briankendall** [comment]
@tuananh No I don't believe you should -- that's not standard on those OSs

**Comment by tuananh** [comment]
@briankendall  i will register the hide window menu on macOS only.

**Comment by zcbenz** [comment]
The "Hide" feature on macOS actually does not really hide the windows, it works by hiding the app itself, and windows can be bring back by clicking the dock icon.

To implement this I need to add some APIs in Yue library, I'll fix the issue once the new version of Yue library is ready. But still thanks for working on this.

**Pull request closed without merging**
